### ISSUE TITLE
Update project information in pom.xml

### ISSUE THREAD

**Issue by takezoe** [takezoe/mirage#40]
We should update some parts of project information in `pom.xml`.
Also we need assembly plugin no longer.

**Comment by takezoe** [comment]
In addition, it might be good to remove bat files for Windows too.

**Comment by aadrian** [comment]
@takezoe 
> We should update some parts of project information in pom.xml

What parts of the ```pom.xml``` still need update besides using newer versions for some of the dependencies?

**Comment by takezoe** [comment]
- Add @aadrian to developer section :-)
- Remove mailingLists and repositories section

The mailing list is no longer active. Also mirage no longer needs the amateras repository.

**Comment by aadrian** [comment]
project information updated

**Comment by takezoe** [comment]
@aadrian Thanks!!
