### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by takezoe** [takezoe/mirage#41]

**Comment by aadrian** [comment]
@takezoe there is a simple https://github.com/takezoe/mirage/blob/master/.travis.yml there, but Travis-CI is not letting me configure it since I'm not the owner, nor is the project not part of an organization: so they are ignoring the commit rights I have to your repo.

**Comment by takezoe** [comment]
Thanks. I will do it because I would like to update pom.xml together.
Moving to organization is one option in the future.

**Comment by aadrian** [comment]
> Moving to organization is one option in the future.

Just created one https://github.com/mirage-sql

**Comment by aadrian** [comment]
and added you as an owner to it.

**Comment by takezoe** [comment]
Done.
